apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: codebase-wiki
  labels:
    app.kubernetes.io/part-of: codebase-wiki
type: Opaque
data:
  # Base64 encoded — generate dengan: echo -n "value" | base64
  # Default values di bawah HANYA untuk development, WAJIB diganti untuk production
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQGRhdGFiYXNlLXN2Yzo1NDMyL2NvZGViYXNlX3dpa2k=
  OPENAI_API_KEY: Y2hhbmdlbWU=
  GEMINI_API_KEY: QVEuQWI4Uk42STlodkc0a29HTW5GX0xyOTlHZFdWNm1lUzNKeXZwbDZGOWlGdkFrWER5VXc=
  ENCRYPTION_SECRET_KEY: Y2hhbmdlbWUzMmNoYXJzZWNyZXRrZXkxMjM0NTY=
  NEXTAUTH_SECRET: Y2hhbmdlbWU=
