apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: codebase-wiki
  labels:
    app: database
    app.kubernetes.io/part-of: codebase-wiki
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: codebase-wiki
  labels:
    app: database
    app.kubernetes.io/part-of: codebase-wiki
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: postgres-pv
