apiVersion: v1
kind: Service
metadata:
  name: database-svc
  namespace: codebase-wiki
  labels:
    app: database
    app.kubernetes.io/part-of: codebase-wiki
spec:
  selector:
    app: database
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  type: ClusterIP
