apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: codebase-wiki
  labels:
    app: frontend
    app.kubernetes.io/part-of: codebase-wiki
spec:
  selector:
    app: frontend
  ports:
    - port: 4000
      targetPort: 4000
      name: http
  type: NodePort
