apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: codebase-wiki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/devopsTubes-codebase/codebase-wiki-k8s.git
    targetRevision: main
    path: k8s/codebase-wiki
  destination:
    server: https://kubernetes.default.svc
    namespace: codebase-wiki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
