apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: codebase-wiki
  labels:
    app: backend
    app.kubernetes.io/part-of: codebase-wiki
spec:
  selector:
    app: backend
  ports:
    - port: 4000
      targetPort: 4000
      name: http
  type: ClusterIP
